### ISSUE TITLE
Don't wouldn't gibi kelimelerde sonuç vermiyor

### ISSUE THREAD

**Issue by cartals** [mesuutt/turengo#2]
turengo don't yazıyorum terminalde > bu çıkıyor ctrl c ile iptal ediyorum turengo wouldn't yazıyorum, shouldn't yazıyorum yine aynı bunu engelleme yolu yok mu?

**Comment by mesuutt** [comment]
@cartals `don't`, `wouldn't` gibi kelimeler icierisnde bulunan `'` isareti terminalde ozel bir anlam ifade ettigi icin calismaz, icerisinde tirnak gecen kelimeleri su sekilde arama yapabilirsiniz: 

`turengo "don't"`
